name = "medium"
compatibility_date = "2024-10-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOWNlNTY2MDgtZDAxMy00NDVjLTk3ZjItZjE1ZGM2YzAzODlhIiwidGVuYW50X2lkIjoiY2M2ODNhYWY5ZjFlODFiYWI3NDgwZmE3OWE2MzY2MGRmNmJlYWI1NmYxYjA2M2U1NTg5ZTc5NGFhYWUwMzc3MCIsImludGVybmFsX3NlY3JldCI6IjY3ZmU3OWFkLWRhODktNDg3YS1iM2NmLWVjZWYzNzI5MmYyMCJ9.hviSky81VLYIV2QvjG-wY_bxmJdDSbF5Mq68TDwei7E"
YOUR_OPENAI_API_KEY="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"
CLOUDINARY_CLOUD_NAME="dgcjzooxx"
CLOUDINARY_API_KEY="495285587171927"
CLOUDINARY_API_SECRET="PbqQ7hedm0ijvWTU2VrVroLw-P4"
PRESET="ml_default"



JWT_SECRET = "MYSECRETJWT"
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"